[project]
name = "autobot"
version = "0.0.1a1"
dependencies = [
    "httpx >= 0.23.0",
    "autotelegram @ https://github.com/ht-thomas/autotelegram/archive/refs/tags/autotelegram.zip",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
